//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class InteractiveUniversityEntities1 : DbContext
{
    public InteractiveUniversityEntities1()
        : base("name=InteractiveUniversityEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<dbGame> dbGame { get; set; }
    public DbSet<dbProduct> dbProduct { get; set; }
    public DbSet<dbProductState> dbProductState { get; set; }
    public DbSet<dbAvailableGames> dbAvailableGames { get; set; }
    public DbSet<dbFFFactor> dbFFFactor { get; set; }
    public DbSet<dbFFGame> dbFFGame { get; set; }
    public DbSet<dbMarketTemplate> dbMarketTemplate { get; set; }
    public DbSet<dbProductStateTemplate> dbProductStateTemplate { get; set; }
    public DbSet<dbProductTemplate> dbProductTemplate { get; set; }
    public DbSet<dbScenario> dbScenario { get; set; }
    public DbSet<dbMarket> dbMarket { get; set; }
    public DbSet<dbMarketName> dbMarketName { get; set; }
    public DbSet<dbProductName> dbProductName { get; set; }
}
