//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class dbAvailableGames
{
    public int id { get; set; }
    public string gameName { get; set; }
    public string gameType { get; set; }
    public string gameDescription { get; set; }
    public bool available { get; set; }
}

public partial class dbFFFactor
{
    public int id { get; set; }
    public int ffgame_id { get; set; }
    public string force_shortname { get; set; }
    public string force_fullname { get; set; }
    public string factor_shortname { get; set; }
    public string factor_fullname { get; set; }
    public string factor_auspraegung { get; set; }
    public string factor_visualization { get; set; }  //die SVG-Grafik


    public virtual dbFFGame dbFFGame { get; set; }
}

public partial class dbFFGame
{
    public dbFFGame()
    {
        this.dbFFFactor = new HashSet<dbFFFactor>();
    }

    public int id { get; set; }
    public string playergamename { get; set; }
    public Nullable<int> turnbookmark { get; set; }
    public string gamename { get; set; }

    public virtual ICollection<dbFFFactor> dbFFFactor { get; set; }
}

public partial class dbGame
{
    public dbGame()
    {
        this.dbMarket = new HashSet<dbMarket>();
    }

    public int id { get; set; }
    public string playergamename { get; set; }
    public Nullable<int> turnBookmark { get; set; }
    public Nullable<int> maxTurns { get; set; }
    public Nullable<int> maxBadRounds { get; set; }
    public Nullable<int> maxNegativeCF { get; set; }
    public string gameDescription { get; set; }

    public virtual ICollection<dbMarket> dbMarket { get; set; }
}

public partial class dbMarket
{
    public dbMarket()
    {
        this.dbProduct = new HashSet<dbProduct>();
    }

    public int id { get; set; }
    public int game_id { get; set; }
    public string name { get; set; }
    public string type { get; set; }
    public string growth { get; set; }
    public Nullable<int> toBeAddedInTurn { get; set; }
    public Nullable<int> marketLifeTimeUp { get; set; }
    public Nullable<int> marketLifeTimeDown { get; set; }
    public Nullable<int> stepsize_down { get; set; }
    public Nullable<int> stepsize_up { get; set; }

    public virtual dbGame dbGame { get; set; }
    public virtual ICollection<dbProduct> dbProduct { get; set; }
}

public partial class dbMarketName
{
    public dbMarketName()
    {
        this.dbProductName = new HashSet<dbProductName>();
    }

    public int id { get; set; }
    public string marketName { get; set; }
    public string marketType { get; set; }

    public virtual ICollection<dbProductName> dbProductName { get; set; }
}

public partial class dbMarketTemplate
{
    public dbMarketTemplate()
    {
        this.dbProductTemplate = new HashSet<dbProductTemplate>();
    }

    public int id { get; set; }
    public Nullable<int> dbAvailableGames_id { get; set; }
    public string name { get; set; }
    public string type { get; set; }
    public string growth { get; set; }
    public Nullable<double> growth2 { get; set; }
    public Nullable<int> toBeAddedInTurn { get; set; }

    public virtual ICollection<dbProductTemplate> dbProductTemplate { get; set; }
    public virtual dbScenario dbScenario { get; set; }
}

public partial class dbProduct
{
    public dbProduct()
    {
        this.dbProductState = new HashSet<dbProductState>();
    }

    public int id { get; set; }
    public int market_id { get; set; }
    public string name { get; set; }
    public Nullable<int> playerProduct { get; set; }
    public string primaryColor { get; set; }
    public string secondaryColor { get; set; }
    public string advisor_name { get; set; }
    public string advisor_imagesource { get; set; }
    public string advisor_feedback { get; set; }
    public string advisor_enabled { get; set; }

    public virtual ICollection<dbProductState> dbProductState { get; set; }
    public virtual dbMarket dbMarket { get; set; }
}

public partial class dbProductName
{
    public int id { get; set; }
    public int marketName_id { get; set; }
    public string productName { get; set; }
    public string productStrength { get; set; }
    public string productFriendlyness { get; set; }

    public virtual dbMarketName dbMarketName { get; set; }
}

public partial class dbProductState
{
    public int id { get; set; }
    public Nullable<int> product_id { get; set; }
    public Nullable<int> turn { get; set; }
    public Nullable<double> marketshare { get; set; }

    public virtual dbProduct dbProduct { get; set; }
}

public partial class dbProductStateTemplate
{
    public int id { get; set; }
    public Nullable<int> productTemplate_id { get; set; }
    public Nullable<int> turn { get; set; }
    public Nullable<double> marketshare { get; set; }

    public virtual dbProductTemplate dbProductTemplate { get; set; }
}

public partial class dbProductTemplate
{
    public dbProductTemplate()
    {
        this.dbProductStateTemplate = new HashSet<dbProductStateTemplate>();
    }

    public int id { get; set; }
    public int marketTemplate_id { get; set; }
    public string name { get; set; }
    public Nullable<int> playerProduct { get; set; }
    public string primaryColor { get; set; }
    public string secondaryColor { get; set; }

    public virtual dbMarketTemplate dbMarketTemplate { get; set; }
    public virtual ICollection<dbProductStateTemplate> dbProductStateTemplate { get; set; }
}

public partial class dbScenario
{
    public dbScenario()
    {
        this.dbMarketTemplate = new HashSet<dbMarketTemplate>();
    }

    public int id { get; set; }
    public string gameName { get; set; }
    public string gameType { get; set; }

    public virtual ICollection<dbMarketTemplate> dbMarketTemplate { get; set; }
}
